owner: deployphp
repo: status

sites:
  - name: Deployer Site 
    url: https://deployer.org

status-website:
  cname: status.deployer.org
  logoUrl: https://avatars2.githubusercontent.com/u/8088857?s=200&v=4
  name: Deployer
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
